<script setup lang="ts">
import AnalysisNav from "../../../features/analysis/AnalysisNav.vue";
import { useSpeciesPage } from "../../../features/analysis/useSpeciesPage";
const page = useSpeciesPage();
</script>
<template><div class="page-wrap analysis-page mobile-species-page" data-platform-page="mobile"><AnalysisNav /><header><small>{{ page.speciesCount.value }} 种宠物</small><h1>同名对比</h1><p>每张卡片列出跨账号的四项最高值。</p></header><label class="mobile-species-search"><span>搜索</span><input v-model="page.query.value" type="search" placeholder="搜索宠物或账号"></label><section class="mobile-species-list"><article v-for="row in page.rows.value" :key="row.name"><header><div><h2>{{ row.name }}</h2><p>{{ row.accounts.join(" · ") }}</p></div><strong>{{ row.pets.length }} 组</strong></header><div class="mobile-species-metrics"><RouterLink :to="`/assets/pets?selected=${encodeURIComponent(row.bestTalent.id)}`"><span>最高天资</span><b>{{ row.bestTalent.accountId }} {{ row.bestTalent.talent || "-" }}</b></RouterLink><RouterLink :to="`/assets/pets?selected=${encodeURIComponent(row.bestAttack.id)}`"><span>最高攻击</span><b>{{ row.bestAttack.accountId }} {{ row.bestAttack.attack }}</b></RouterLink><RouterLink :to="`/assets/pets?selected=${encodeURIComponent(row.bestSpeed.id)}`"><span>最高速度</span><b>{{ row.bestSpeed.accountId }} {{ row.bestSpeed.speed }}</b></RouterLink><RouterLink :to="`/assets/pets?selected=${encodeURIComponent(row.bestSpirit.id)}`"><span>最高灵力</span><b>{{ row.bestSpirit.accountId }} {{ row.bestSpirit.spirit }}</b></RouterLink></div></article></section></div></template>
<style scoped>
.mobile-species-page{width:100%;padding:6px 12px 112px}.mobile-species-page>header{padding:12px 2px}.mobile-species-page>header small{color:#c44d00;font-size:11px;font-weight:850}.mobile-species-page>header h1{font-size:25px}.mobile-species-page>header p,.mobile-species-search span{color:#697386;font-size:11px}.mobile-species-search{display:grid;gap:5px;margin-bottom:10px}.mobile-species-search input{min-height:46px}.mobile-species-list{display:grid;gap:9px}.mobile-species-list>article{overflow:hidden;border:1px solid rgba(60,60,67,.15);border-radius:12px;background:#fff}.mobile-species-list article>header{display:flex;align-items:center;justify-content:space-between;padding:10px 12px;background:#faf8f5}.mobile-species-list h2{font-size:16px}.mobile-species-list header p,.mobile-species-metrics span{color:#697386;font-size:10px}.mobile-species-list header>strong{color:#a9430c;font-size:12px}.mobile-species-metrics{display:grid;grid-template-columns:1fr 1fr}.mobile-species-metrics a{display:grid;gap:4px;padding:11px 12px;border-top:1px solid rgba(60,60,67,.1)}.mobile-species-metrics a:nth-child(odd){border-right:1px solid rgba(60,60,67,.1)}.mobile-species-metrics b{font-size:12px}
.mobile-species-list header p,
.mobile-species-metrics span { font-size: 11px; }
</style>
