<script setup lang="ts">
import AnalysisNav from "../../../features/analysis/AnalysisNav.vue";
import { useRecommendationsPage } from "../../../features/analysis/useRecommendationsPage";
const page = useRecommendationsPage();
</script>
<template><div class="page-wrap analysis-page mobile-recommendations-page" data-platform-page="mobile"><AnalysisNav /><header><small>四类候选</small><h1>推荐分析</h1><p>按用途先缩小范围，再进入宠物详情核对。</p></header><label class="mobile-analysis-search"><span>筛选推荐</span><input v-model="page.query.value" type="search" placeholder="筛选账号、宠物或技能"></label><section class="mobile-recommendation-groups"><article v-for="group in page.recommendations.value" :key="group.key"><header><div><h2>{{ group.title }}</h2><p>{{ group.metric }} · {{ group.rows.length }} 条</p></div></header><RouterLink v-for="pet in group.rows" :key="pet.id" :to="`/assets/pets?selected=${encodeURIComponent(pet.id)}`"><b class="account-code">{{ pet.accountId }}</b><div><strong>{{ pet.name }}</strong><span>{{ pet.role.primary }} · {{ pet.skills.filter((skill) => skill !== '空').slice(0,2).join(' / ') }}</span></div><em>查看</em></RouterLink><p v-if="!group.rows.length" class="empty">没有匹配候选</p></article></section></div></template>
<style scoped>
.mobile-recommendations-page{width:100%;padding:6px 12px 112px}.mobile-recommendations-page>header{padding:12px 2px}.mobile-recommendations-page>header small{color:#c44d00;font-size:11px;font-weight:850}.mobile-recommendations-page>header h1{font-size:25px}.mobile-recommendations-page>header p,.mobile-analysis-search span{color:#697386;font-size:11px}.mobile-analysis-search{display:grid;gap:5px;margin-bottom:10px}.mobile-analysis-search input{min-height:46px}.mobile-recommendation-groups{display:grid;gap:9px}.mobile-recommendation-groups>article{overflow:hidden;border:1px solid rgba(60,60,67,.15);border-radius:12px;background:#fff}.mobile-recommendation-groups article>header{padding:10px 12px;background:#faf8f5}.mobile-recommendation-groups h2{font-size:16px}.mobile-recommendation-groups header p,.mobile-recommendation-groups a span{color:#697386;font-size:10px}.mobile-recommendation-groups a{min-height:58px;display:grid;grid-template-columns:38px minmax(0,1fr) auto;align-items:center;gap:8px;padding:8px 11px;border-top:1px solid rgba(60,60,67,.1)}.mobile-recommendation-groups a div{display:grid;gap:3px}.mobile-recommendation-groups a strong{font-size:13px}.mobile-recommendation-groups a em{color:#a9430c;font-size:11px;font-style:normal;font-weight:800}.mobile-recommendation-groups .empty{padding:20px;text-align:center;color:#697386;font-size:11px}
.mobile-recommendation-groups header p,
.mobile-recommendation-groups a span { font-size: 11px; }
</style>
