<script setup lang="ts">
import AnalysisNav from "../../../features/analysis/AnalysisNav.vue";
import MatrixGrid from "../../../features/analysis/MatrixGrid.vue";
import { useMatrixPage } from "../../../features/analysis/useMatrixPage";
const page = useMatrixPage();
</script>
<template><div class="page-wrap analysis-page matrix-page mobile-matrix-page" data-platform-page="mobile"><AnalysisNav /><header class="mobile-matrix-hero"><div><small>五账号横向比较</small><h1>固定矩阵</h1><p>{{ page.filledCount.value }} / {{ page.totalSlots.value }} 个位置已匹配</p></div><strong>{{ page.coverageRate.value }}%</strong></header><div class="mobile-matrix-tabs matrix-group-tabs" role="tablist" aria-label="阵容分类"><button v-for="(item,index) in page.groups" :id="`matrix-group-${index}`" :key="item" type="button" role="tab" :aria-selected="page.group.value === item" :class="{ active: page.group.value === item }" @click="page.group.value = item"><span>{{ page.groupCopy[item].short }}</span></button></div><details class="mobile-matrix-options"><summary>显示设置 · {{ page.visibleFieldCount.value }} 类信息</summary><fieldset class="matrix-options"><legend>显示内容</legend><label><input v-model="page.ui.matrixDisplay.stats" type="checkbox"><span>属性</span></label><label><input v-model="page.ui.matrixDisplay.aptitudes" type="checkbox"><span>资质</span></label><label><input v-model="page.ui.matrixDisplay.skills" type="checkbox"><span>技能</span></label><label><span>密度</span><select v-model="page.ui.matrixDensity" aria-label="矩阵显示密度"><option value="compact">紧凑</option><option value="comfortable">舒展</option></select></label></fieldset></details><p class="matrix-scroll-hint">可左右滚动；账号表头和位置列会保持可见。</p><MatrixGrid :page="page" /></div></template>
<style scoped>
.mobile-matrix-page{width:100%;padding:6px 12px 112px}.mobile-matrix-hero{display:flex;align-items:center;justify-content:space-between;padding:12px 2px}.mobile-matrix-hero small{color:#c44d00;font-size:11px;font-weight:850}.mobile-matrix-hero h1{font-size:25px}.mobile-matrix-hero p{color:#697386;font-size:11px}.mobile-matrix-hero>strong{display:grid;place-items:center;width:58px;height:58px;border-radius:50%;color:#fff;background:#b54b12;font-size:17px}.mobile-matrix-tabs{display:flex;overflow:auto;gap:6px;margin-bottom:8px;padding-bottom:2px}.mobile-matrix-tabs button{min-width:max-content;min-height:42px;padding:0 12px;border:1px solid rgba(60,60,67,.15);border-radius:10px;background:#fff}.mobile-matrix-tabs button.active{color:#9f3b08;border-color:#d28a61;background:#fff3eb}.mobile-matrix-options{margin-bottom:8px;border:1px solid rgba(60,60,67,.15);border-radius:10px;background:#fff}.mobile-matrix-options summary{min-height:44px;display:flex;align-items:center;padding:0 12px;font-size:12px;font-weight:800}.mobile-matrix-options .matrix-options{padding:9px 12px;border-top:1px solid rgba(60,60,67,.1)}.mobile-matrix-page .matrix-scroll-hint{margin:7px 2px;font-size:10px}
.mobile-matrix-page .matrix-scroll-hint { font-size: 11px; }
</style>
