import { createRouter, createWebHashHistory, type RouteRecordRaw } from "vue-router";

export const routes: RouteRecordRaw[] = [
  { path: "/", name: "dashboard", component: () => import("../features/home/HomePage.vue"), meta: { title: "本周", section: "home", mobileSection: "home" } },
  { path: "/record", name: "record", component: () => import("../features/mobile/RecordPage.vue"), meta: { title: "录入", section: "record", mobileSection: "record", immersive: true } },
  { path: "/week", name: "week", component: () => import("../features/mobile/WeekPage.vue"), meta: { title: "本周小结", section: "week", mobileSection: "week", immersive: true } },
  { path: "/weekly", redirect: "/week" },
  { path: "/resources", name: "resources", component: () => import("../features/mobile/ResourcesPage.vue"), meta: { title: "资料", section: "resources", mobileSection: "resources", immersive: true } },
  { path: "/library", redirect: "/resources" },
  { path: "/accounts/:accountId(FC|LG1|PT|LG2|MYT)", name: "account", component: () => import("../features/accounts/AccountPage.vue"), meta: { title: "账号详情", section: "accounts", mobileSection: "resources" } },
  { path: "/assets/pets", name: "pets", component: () => import("../features/assets/PetsPage.vue"), meta: { title: "宠物资产", section: "assets", mobileSection: "resources" } },
  { path: "/assets/equipment", name: "equipment", component: () => import("../features/assets/EquipmentPage.vue"), meta: { title: "装备资产", section: "assets", mobileSection: "resources" } },
  { path: "/assets/skills", name: "skills", component: () => import("../features/assets/SkillsPage.vue"), meta: { title: "技能资料", section: "assets", mobileSection: "resources" } },
  { path: "/assets/evidence", name: "evidence", component: () => import("../features/assets/EvidencePage.vue"), meta: { title: "截图证据", section: "assets", mobileSection: "resources" } },
  { path: "/plans/upgrades", redirect: "/plans/gems" },
  { path: "/plans/gems", name: "gem-plan", component: () => import("../features/plans/UpgradesPage.vue"), meta: { title: "宝石计划", section: "plans", mobileSection: "more" } },
  { path: "/plans/beasts", name: "beasts", component: () => import("../features/plans/BeastsPage.vue"), meta: { title: "神兽主线任务", section: "plans", mobileSection: "more" } },
  { path: "/plans/tasks", name: "plan-tasks", component: () => import("../features/plans/TaskMaintenancePage.vue"), meta: { title: "任务维护", section: "plans", mobileSection: "record" } },
  { path: "/plans/timeline", name: "timeline", component: () => import("../features/plans/TimelinePage.vue"), meta: { title: "五号主线概览", section: "plans", mobileSection: "more" } },
  { path: "/plans/parameters", name: "plan-parameters", component: () => import("../features/plans/PlanParametersPage.vue"), meta: { title: "计划参数", section: "plans", mobileSection: "more" } },
  { path: "/analysis/recommendations", name: "recommendations", component: () => import("../features/analysis/RecommendationsPage.vue"), meta: { title: "推荐分析", section: "analysis", mobileSection: "resources" } },
  { path: "/analysis/species", name: "species", component: () => import("../features/analysis/SpeciesPage.vue"), meta: { title: "同名对比", section: "analysis", mobileSection: "resources" } },
  { path: "/analysis/matrix", name: "matrix", component: () => import("../features/analysis/MatrixPage.vue"), meta: { title: "固定矩阵", section: "analysis", mobileSection: "resources" } },
  { path: "/publish", name: "publish", component: () => import("../features/publish/PublishPage.vue"), meta: { title: "内容发布", section: "publish", mobileSection: "more" } },
  { path: "/data", redirect: "/data/inventory" },
  { path: "/data/resources", redirect: "/data/inventory" },
  { path: "/data/tasks", redirect: "/plans/tasks" },
  { path: "/data/inventory", name: "data-inventory", component: () => import("../features/data/DataCenterPage.vue"), meta: { title: "库存资料", section: "data", mobileSection: "resources" } },
  { path: "/data/market", name: "data-market", component: () => import("../features/data/DataCenterPage.vue"), meta: { title: "宝石行情", section: "data", mobileSection: "record" } },
  { path: "/data/sources", name: "data-sources", component: () => import("../features/data/DataCenterPage.vue"), meta: { title: "数据来源", section: "data", mobileSection: "resources" } },
  { path: "/settings", name: "settings", component: () => import("../features/settings/SettingsPage.vue"), meta: { title: "界面设置", section: "data", mobileSection: "more" } },
  { path: "/:pathMatch(.*)*", redirect: "/" },
];

export const router = createRouter({ history: createWebHashHistory(), routes, scrollBehavior: () => ({ top: 0 }) });
