import { createRouter, createWebHashHistory, type RouteRecordRaw } from "vue-router";
import {
  accountPlatformPage,
  beastsPlatformPage,
  dataInventoryPlatformPage,
  dataMarketPlatformPage,
  dataSourcesPlatformPage,
  earningsPlatformPage,
  equipmentPlatformPage,
  evidencePlatformPage,
  gemPlanPlatformPage,
  matrixPlatformPage,
  petsPlatformPage,
  planParametersPlatformPage,
  recordPlatformPage,
  recommendationsPlatformPage,
  resourcesPlatformPage,
  skillsPlatformPage,
  settingsPlatformPage,
  speciesPlatformPage,
  taskPlatformPage,
  timelinePlatformPage,
  publishPlatformPage,
  weekPlatformPage,
} from "./platformPages";

export const routes: RouteRecordRaw[] = [
  { path: "/", name: "dashboard", component: () => import("../features/home/HomePage.vue"), meta: { title: "本周", section: "home", mobileSection: "home", desktopSection: "home" } },
  { path: "/record", name: "record", component: recordPlatformPage.component, meta: { title: "录入", section: "record", mobileSection: "record", desktopSection: "record", immersive: true } },
  { path: "/earnings", name: "earnings", component: earningsPlatformPage.component, meta: { title: "实际所得", section: "earnings", mobileSection: "more", desktopSection: "earnings", immersive: true } },
  { path: "/week", name: "week", component: weekPlatformPage.component, meta: { title: "本周小结", section: "week", mobileSection: "week", desktopSection: "week", immersive: true } },
  { path: "/weekly", redirect: "/week" },
  { path: "/resources", name: "resources", component: resourcesPlatformPage.component, meta: { title: "资料", section: "resources", mobileSection: "resources", desktopSection: "resources", immersive: true } },
  { path: "/library", redirect: "/resources" },
  { path: "/accounts/:accountId(FC|LG1|PT|LG2|MYT)", name: "account", component: accountPlatformPage.component, meta: { title: "账号详情", section: "accounts", mobileSection: "resources" } },
  { path: "/assets/pets", name: "pets", component: petsPlatformPage.component, meta: { title: "宠物资产", section: "assets", mobileSection: "resources" } },
  { path: "/assets/equipment", name: "equipment", component: equipmentPlatformPage.component, meta: { title: "装备资产", section: "assets", mobileSection: "resources" } },
  { path: "/assets/skills", name: "skills", component: skillsPlatformPage.component, meta: { title: "技能资料", section: "assets", mobileSection: "resources" } },
  { path: "/assets/evidence", name: "evidence", component: evidencePlatformPage.component, meta: { title: "截图证据", section: "assets", mobileSection: "resources" } },
  { path: "/plans/upgrades", redirect: "/plans/gems" },
  { path: "/plans/gems", name: "gem-plan", component: gemPlanPlatformPage.component, meta: { title: "宝石计划", section: "plans", mobileSection: "more" } },
  { path: "/plans/beasts", name: "beasts", component: beastsPlatformPage.component, meta: { title: "神兽主线任务", section: "plans", mobileSection: "more" } },
  { path: "/plans/tasks", name: "plan-tasks", component: taskPlatformPage.component, meta: { title: "任务", section: "plans", mobileSection: "tasks", desktopSection: "tasks", immersive: true } },
  { path: "/plans/timeline", name: "timeline", component: timelinePlatformPage.component, meta: { title: "五号主线概览", section: "plans", mobileSection: "more" } },
  { path: "/plans/parameters", name: "plan-parameters", component: planParametersPlatformPage.component, meta: { title: "计划参数", section: "plans", mobileSection: "more" } },
  { path: "/analysis/recommendations", name: "recommendations", component: recommendationsPlatformPage.component, meta: { title: "推荐分析", section: "analysis", mobileSection: "resources" } },
  { path: "/analysis/species", name: "species", component: speciesPlatformPage.component, meta: { title: "同名对比", section: "analysis", mobileSection: "resources" } },
  { path: "/analysis/matrix", name: "matrix", component: matrixPlatformPage.component, meta: { title: "固定矩阵", section: "analysis", mobileSection: "resources" } },
  { path: "/publish", name: "publish", component: publishPlatformPage.component, meta: { title: "内容发布", section: "publish", mobileSection: "more" } },
  { path: "/data", redirect: "/data/inventory" },
  { path: "/data/resources", redirect: "/data/inventory" },
  { path: "/data/tasks", redirect: "/plans/tasks" },
  { path: "/data/inventory", name: "data-inventory", component: dataInventoryPlatformPage.component, meta: { title: "库存资料", section: "data", mobileSection: "resources" } },
  { path: "/data/market", name: "data-market", component: dataMarketPlatformPage.component, meta: { title: "宝石行情", section: "data", mobileSection: "record", desktopSection: "record" } },
  { path: "/data/sources", name: "data-sources", component: dataSourcesPlatformPage.component, meta: { title: "数据来源", section: "data", mobileSection: "resources" } },
  { path: "/settings", name: "settings", component: settingsPlatformPage.component, meta: { title: "界面设置", section: "data", mobileSection: "more" } },
  { path: "/:pathMatch(.*)*", redirect: "/" },
];

export const router = createRouter({ history: createWebHashHistory(), routes, scrollBehavior: () => ({ top: 0 }) });
