import type { AccountId } from "../domain/types";

const color = {
  brand: "#006b63",
  accent: "#00796f",
  canvas: "#edf3f1",
  white: "#ffffff",
  glass: "rgba(255, 255, 255, .94)",
  glassStrong: "rgba(255, 255, 255, .96)",
  surfaceMuted: "#f2f6f5",
  surfaceSubtle: "#f7f9f8",
  surfaceNearWhite: "#fbfcfc",
  positiveSurface: "#e7f3f0",
  positiveSurfaceStrong: "#e8f3f1",
  warningSurface: "#fff6e6",
  dangerSurface: "#faeaea",
  textPrimary: "#142522",
  textStrong: "#20312e",
  textBody: "#40534f",
  textCaption: "#60736f",
  textSecondary: "#657975",
  textMuted: "#71817e",
  textFaint: "#899793",
  textDisabled: "#9aa8a4",
  borderStrong: "#d4dfdd",
  borderDefault: "#dce5e3",
  borderSubtle: "#e0e8e6",
  borderMedia: "#cddbd8",
  positive: "#08765a",
  positiveBorder: "#0a8a68",
  positiveBorderSoft: "#b9dcca",
  positiveBorderStrong: "#a7d4c9",
  negative: "#b42318",
  danger: "#a33838",
  dangerBorder: "#bf4b45",
  warning: "#9a5a00",
  warningStrong: "#8a5a00",
  warningBorder: "#c47a00",
  warningBorderSoft: "#ead3a8",
  warningText: "#755006",
  warningTextMuted: "#75664e",
  tealGlow: "rgba(0, 121, 111, .12)",
  transparent: "rgba(255, 255, 255, 0)",
  blueGlow: "rgba(18, 103, 143, .08)",
  warmGlow: "rgba(196, 108, 0, .08)",
  forestGlow: "rgba(24, 90, 76, .08)",
  cardShadow: "rgba(10, 41, 35, .08)",
  mediaFrame: "#10211f",
  mediaBackground: "#071411",
} as const;

export const shareImageAccountColors: Readonly<Record<AccountId, string>> = {
  FC: "#12678f",
  LG1: "#6446a6",
  PT: color.danger,
  LG2: color.warningStrong,
  MYT: "#28764a",
};

export const shareImagePalette = {
  brand: {
    primary: color.brand,
    accent: color.accent,
  },
  canvas: {
    background: color.canvas,
  },
  surface: {
    default: color.white,
    glass: color.glass,
    glassStrong: color.glassStrong,
    muted: color.surfaceMuted,
    subtle: color.surfaceSubtle,
    nearWhite: color.surfaceNearWhite,
  },
  text: {
    primary: color.textPrimary,
    strong: color.textStrong,
    body: color.textBody,
    caption: color.textCaption,
    secondary: color.textSecondary,
    muted: color.textMuted,
    faint: color.textFaint,
    disabled: color.textDisabled,
  },
  border: {
    strong: color.borderStrong,
    default: color.borderDefault,
    subtle: color.borderSubtle,
    media: color.borderMedia,
  },
  status: {
    positive: {
      foreground: color.positive,
      background: color.positiveSurface,
      backgroundStrong: color.positiveSurfaceStrong,
      border: color.positiveBorder,
      borderSoft: color.positiveBorderSoft,
      borderStrong: color.positiveBorderStrong,
    },
    negative: {
      foreground: color.negative,
    },
    warning: {
      foreground: color.warning,
      foregroundStrong: color.warningStrong,
      text: color.warningText,
      textMuted: color.warningTextMuted,
      background: color.warningSurface,
      border: color.warningBorder,
      borderSoft: color.warningBorderSoft,
    },
    danger: {
      foreground: color.danger,
      background: color.dangerSurface,
      border: color.dangerBorder,
    },
  },
  gradient: {
    tealGlow: color.tealGlow,
    transparent: color.transparent,
    blueGlow: color.blueGlow,
    warmGlow: color.warmGlow,
    forestGlow: color.forestGlow,
  },
  shadow: {
    card: color.cardShadow,
  },
  media: {
    frame: color.mediaFrame,
    background: color.mediaBackground,
  },
} as const;
